---
- name: 删除 ceiling 组设备 Raw_Data 下的所有 .npy 文件
  hosts: ceiling
  become: true
  vars:
    # 替换成你真实的路径
    raw_data_path: "/home/pi/Techtile_Channel_Measurement/Raw_Data"

  tasks:
    - name: 删除所有 .npy 文件
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ npy_files.files }}"
      when:
        - raw_data_stat.stat.exists
        - npy_files.matched > 0
