---
- name: 强制清空 ceiling 组主机上 Raw_Data
  hosts: ceiling
  become: true
  vars:
    raw_data_path: "/home/pi/Techtile_Channel_Measurement/Raw_Data"

  tasks:
    - name: 检查 Raw_Data 目录是否存在
      stat:
        path: "{{ raw_data_path }}"
      register: raw_data_stat

    - name: 取消 Raw_Data 目录及子文件的不可变属性
      command: chattr -R -i "{{ raw_data_path }}"
      args:
        warn: false
      when: raw_data_stat.stat.exists

    - name: 删除 Raw_Data 目录（含所有内容）
      file:
        path: "{{ raw_data_path }}"
        state: absent
      when: raw_data_stat.stat.exists

    - name: 重建 Raw_Data 目录
      file:
        path: "{{ raw_data_path }}"
        state: directory
        mode: '0755'
      when: raw_data_stat.stat.exists

    - name: 输出结果
      debug:
        msg: "已删除并重建 {{ raw_data_path }}。"
      when: raw_data_stat.stat.exists
