---
- name: Pull GitHub repository code on ceiling
  hosts: ceiling
  become: yes  # Use root privileges if needed; remove if not necessary
  tasks:
    - name: Clone GitHub repository
      git:
        repo: 'https://github.com/techtile-by-dramco/DLI_Validation.git'
        dest: /home/pi/DLI_Validation
        version: master  # Or the branch/tag/commit you need
        force: yes     # Force update if needed
